repos:
  - repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
    - id: black
      language_version: python3.9
      args: [
        "-l", "92",
        "--target-version", "py39"
      ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: requirements-txt-fixer
    - id: mixed-line-ending
  - repo: https://github.com/pycqa/pylint
    rev: v2.12.2
    hooks:
    - id: pylint
      args: [
        "--disable=import-error,too-many-locals,too-many-locals,too-many-branches,too-many-statements",
        "--disable=too-many-arguments,too-many-instance-attributes,duplicate-code"
      ]
      exclude: (?x)^(test_(.+)|time_(.+))$